### PR TITLE
Initial project configurations

### PR DESCRIPTION
**Pull request by hanyelC**

### CODE REVIEW

**Review by MullerHub — COMMENTED** [review]
lgtm

**Review by viniciuscosmome — COMMENTED** [review]
Suggestion: Add in "tsconfig.json".
1. Compile only the changes made to the changed files:
```
  "incremental": true
```

2. Defines the location where the ".tsbuildinfo" file will be saved:
```
  "tsBuildInfoFile": ".tsbuildinfo"
```

**Review by MullerHub — DISMISSED** [review]
it's ok

**Review by viniciuscosmome — DISMISSED** [review]
Lgtm!

**Comment by senegalha** [comment]
LGTM.

**Review by senegalha — APPROVED** [review]

**Review by viniciuscosmome — APPROVED** [review]
Lgtm

**Review by MullerHub — APPROVED** [review]
Good job

**Pull request merged**
